{'name': 'Re-Watt ERP - Qualité batterie < 60 V',
 'version': '1.1.0',
 'category': 'Services/Repair',
 'summary': 'Pivot atelier batterie : champs batterie, contrainte < 60 V, checklist qualité, diagnostics et rapport technicien.',
 'author': 'Re-Watt ERP',
 'license': 'LGPL-3',
 'depends': ['mail',
             'stock',
             'product',
             'sav_magasin_core',
             'sav_magasin_stock',
             'sav_magasin_repair',
             'sav_magasin_knowledge'],
 'data': ['security/ir.model.access.csv',
          'views/battery_model_views.xml',
          'views/battery_checklist_views.xml',
          'views/battery_diagnostic_views.xml',
          'views/battery_test_views.xml',
          'views/sav_order_battery_views.xml',
          'views/battery_create_wizard_views.xml',
          'views/menu.xml',
          'reports/battery_technician_report.xml'],
 'installable': True,
 'application': False,
 'post_init_hook': 'post_init_hook'}
